import "../globals.css";
import DashboardNavabr from "@/components/dashboard/DashboardNavabr";
import DashboardNavList from "@/components/dashboard/DashboardNavList";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen ">
      <div className="hidden md:block w-[280px]">
        <DashboardNavList />
      </div>
      <div className="min-h-[calc(100vh-250px)] w-full bg-[#F5F6FA] overflow-y-scroll pb-10">
        <DashboardNavabr />
        <div className="px-4"> {children}</div>
      </div>
    </div>
  );
}
