import "../globals.css";
import DashboardNavabr from "@/components/dashboard/DashboardNavabr";
import DashboardNavList from "@/components/dashboard/DashboardNavList";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex">
      <div className="hidden md:block w-80">
        <DashboardNavList />
      </div>
      <div className="min-h-[calc(100vh-250px)] w-full">
        <DashboardNavabr />
        <div className="px-2"> {children}</div>
      </div>
    </div>
  );
}
