import { Mulish } from "next/font/google";
import "./globals.css";
import AuthProvider from "./lib/authProvider";
import { Toaster } from "react-hot-toast";

const mulish = Mulish({ weight: "700", subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
