import Footer from "@/components/Shared/Footer";
import "../globals.css";
import Navbar from "@/components/Shared/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <div
        className={``}
      >
        <Navbar/>
        {children}
        <Footer/>
      </div>
  
  );
}
